apiVersion: v1
kind: Service
metadata:
  name: registration-service
  namespace: arch-analyzer-api
  labels:
    app.kubernetes.io/name: registration
    app.kubernetes.io/part-of: arch-analyzer
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: registration-service
  ports:
    - port: 5002
      targetPort: 5002
