// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdensDbContext))]
    [Migration("20260430011114_updatemap_relatorio")]
    partial class updatemap_relatorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Analise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("analise", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Diagrama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnaliseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<Guid>("IdRelatorio")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("TipoDiagrama")
                        .HasColumnType("text");

                    b.Property<string>("URLS3Diagrama")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseId");

                    b.ToTable("diagrama", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Error", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("error", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Relatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<Guid?>("IdDiagrama")
                        .HasColumnType("uuid")
                        .HasColumnName("id_diagrama");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("URLS3Relatorio")
                        .HasColumnType("text")
                        .HasColumnName("urls3_relatorio");

                    b.HasKey("Id");

                    b.HasIndex("IdDiagrama")
                        .IsUnique();

                    b.ToTable("relatorio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Diagrama", b =>
                {
                    b.HasOne("Domain.Entities.Analise", null)
                        .WithMany("Diagramas")
                        .HasForeignKey("AnaliseId");
                });

            modelBuilder.Entity("Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("Domain.Entities.Diagrama", "Diagrama")
                        .WithOne("Relatorio")
                        .HasForeignKey("Domain.Entities.Relatorio", "IdDiagrama");

                    b.Navigation("Diagrama");
                });

            modelBuilder.Entity("Domain.Entities.Analise", b =>
                {
                    b.Navigation("Diagramas");
                });

            modelBuilder.Entity("Domain.Entities.Diagrama", b =>
                {
                    b.Navigation("Relatorio");
                });
#pragma warning restore 612, 618
        }
    }
}
