// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdensDbContext))]
    partial class OrdensDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Analise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("analise", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Diagrama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnaliseId")
                        .HasColumnType("uuid")
                        .HasColumnName("analise_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<Guid>("IdRelatorio")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("TipoDiagrama")
                        .HasColumnType("text");

                    b.Property<string>("URLS3Diagrama")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseId");

                    b.ToTable("diagrama", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Error", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("error", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Relatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Componentes_Identificado")
                        .HasColumnType("jsonb")
                        .HasColumnName("componentes_identificado");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<Guid?>("IdDiagrama")
                        .HasColumnType("uuid")
                        .HasColumnName("id_diagrama");

                    b.Property<string>("Message_Error")
                        .HasColumnType("text")
                        .HasColumnName("message_error");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Recomendacao")
                        .HasColumnType("jsonb")
                        .HasColumnName("recomendacao");

                    b.Property<string>("Risco_Arquitetura")
                        .HasColumnType("jsonb")
                        .HasColumnName("risco_arquitetura");

                    b.Property<Guid?>("Soat_Analysis_Id")
                        .HasColumnType("uuid")
                        .HasColumnName("soat_analysis_id");

                    b.HasKey("Id");

                    b.HasIndex("IdDiagrama")
                        .IsUnique();

                    b.ToTable("relatorio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Diagrama", b =>
                {
                    b.HasOne("Domain.Entities.Analise", "Analise")
                        .WithMany("Diagramas")
                        .HasForeignKey("AnaliseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analise");
                });

            modelBuilder.Entity("Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("Domain.Entities.Diagrama", "Diagrama")
                        .WithOne("Relatorio")
                        .HasForeignKey("Domain.Entities.Relatorio", "IdDiagrama");

                    b.Navigation("Diagrama");
                });

            modelBuilder.Entity("Domain.Entities.Analise", b =>
                {
                    b.Navigation("Diagramas");
                });

            modelBuilder.Entity("Domain.Entities.Diagrama", b =>
                {
                    b.Navigation("Relatorio");
                });
#pragma warning restore 612, 618
        }
    }
}
